### 1. Array

#Arrays

In [1]:
import array


In [30]:
arr1 = array.array('i',[10, 20, 30, 40, 50,])
print(arr1)

array('i', [10, 20, 30, 40, 50])


In [31]:
arr2 =array.array('i',[60, 70, 80])
print(arr2)

array('i', [60, 70, 80])


In [32]:
#access 

arr1[2]

30

In [33]:
arr1[3]

40

In [34]:
#traversal
for element in arr1:
    print(element, end=" ")
    

10 20 30 40 50 

In [35]:
#insertion
arr1.insert(3,35)
print(arr1)

array('i', [10, 20, 30, 35, 40, 50])


In [36]:
# deletion

arr1.remove(30)
print(arr1)

array('i', [10, 20, 35, 40, 50])


In [37]:
# updation
arr1[2] = 30
print(arr1)

array('i', [10, 20, 30, 40, 50])


In [40]:
# sorting

arr3 = array.array('i', [4, 7, 3, 9 ,2, 6])
print(arr3)

array('i', [4, 7, 3, 9, 2, 6])


In [42]:
sorted_arr = array.array('i', sorted(arr3))
print(sorted_arr)

array('i', [2, 3, 4, 6, 7, 9])


In [43]:
# merging

arr1

array('i', [10, 20, 30, 40, 50])

In [44]:
arr2

array('i', [60, 70, 80])

In [47]:
arr4 = arr1 + arr2

In [48]:
#splitting 

ix = int(len(arr4)/2)
ix

4

In [49]:
arr4[:ix]

array('i', [10, 20, 30, 40])

In [50]:
arr4[ix:]

array('i', [50, 60, 70, 80])

### 2. numpy

In [51]:
import numpy as np

In [54]:
# creation 
np1 = np.array([10 , 20, 30, 40, 50])
np2 = np.array([50, 60, 70])
print(np1)
print(np2)

[10 20 30 40 50]
[50 60 70]


In [55]:
# access
np1[0]


np.int64(10)

In [57]:
for ele in np1:
    print(ele, end=" ")

10 20 30 40 50 

In [58]:
# traverm
for ele in np1:
    print(ele, end=" ")

10 20 30 40 50 

In [59]:
# insertion 

np.insert(np1, 3 , 35)

array([10, 20, 30, 35, 40, 50])

In [61]:
# deletion
np.delete(np1,3)

array([10, 20, 30, 50])

In [62]:
# updation
np2[2]= 35
print(np1)

[10 20 30 40 50]


In [63]:
# sorting

np3 = np.array([5, 3, 7, 6, 2, 9])
np3

array([5, 3, 7, 6, 2, 9])

In [64]:
np.sort(np3)

array([2, 3, 5, 6, 7, 9])

In [65]:
# merging 
np1

array([10, 20, 30, 40, 50])

In [66]:
np2

array([50, 60, 35])

In [70]:
np3 =np.concatenate((np1,np2))
np3

array([10, 20, 30, 40, 50, 50, 60, 35])

In [73]:
# spliting 
split1, split2 = np.array_split(np3,2)

In [74]:
split2

array([50, 50, 60, 35])